ecommercewebsiteproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('cart_detail', views.cart_detail, name="cart_detail"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('full_remove/<int:product_id>/', views.full_remove, name="full_remove"),

]

ecommercewebsiteproject/search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"

urlpatterns=[
    path('searchResult', views.searchResult, name='searchResult'),
]

ecommercewebsiteproject/shopping_cart_app/urls.py
from django.urls import path
from . import views
app_name = 'shopping_cart_app'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail')

]

ecommercewebsiteproject/shopping_cart_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shopping_cart_app.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommercewebsiteproject/cart/models.py
from django.db import models
from shopping_cart_app.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250, blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return self.product

ecommercewebsiteproject/search_app/models.py
from django.db import models

# Create your models here.

ecommercewebsiteproject/shopping_cart_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    image = models.ImageField(upload_to='category',blank=True)


    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shopping_cart_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price=models.IntegerField()
    stock=models.IntegerField(blank=True)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('shopping_cart_app:ProdCatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommercewebsiteproject/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shopping_cart_app.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')




def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommercewebsiteproject/search_app/views.py
from django.shortcuts import render
from shopping_cart_app.models import Product
from django.db.models import Q

def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,"search.html",{'query':query, 'products':products})

ecommercewebsiteproject/shopping_cart_app/views.py
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Product,Category


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def ProdCatDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommercewebsiteproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/a076d05399.js' %}"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

</div>
    {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommercewebsiteproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        welcome to the cart
{% endblock %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
        {% if not cart_items %}
<div>
                <div class="text-center">
                    <br>
                    <h1 class="text-center my_title">Your Cart is Empty</h1>
                    <br>
                    <p class="text-center">
                        Please Click <a href="{% url 'shopping_cart_app:allProdCat' %}"> Here</a>
                    </p>
                </div>
            </div>
        {% else %}
            <div>
                <div class="text-center"><br>
                    <h1 class="text-center my_title">
                        Your Cart
                    </h1>
                </div>
            </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th colspan="5"> Your Items </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
            <td>
                <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom image" style="width:8rem; height:8rem;"></a>
            </td>
            <td class="text-lef">
                {{cart_item.product.name}}
                <br>
                SKU:{{cart_item.product.id}}
                <br>
                Unit Price: {{cart_item.product.price}}
                QTY : {{cart_item.quantity}} x $ {{cart_item.product.price}}
            </td>
            <td>
                ${{cart_item.sub_total}}
            </td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <td>
                <a href="{% url 'cart:add_cart' cart_item.product.id %}"> <i class="fas fa-plus custom_icon"></i></a>
                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i> </a>
            </td>
            {% else %}
            <td>
                &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa=minus custom_icon"></i></a>&nbsp;
                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa=trash-alt custom_icon"></i> </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
             <tr>
            <th> Check Out </th>
        </tr>
        </thead>
            <tbody>
            <tr>
                <td>
                    Please review your cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
            <td class="text-left">
                Your total is <strong>${{ total }}</strong>
            </td>
            </tr>
            </tbody>
        </table>
            <div class="mx-auto">
                <a href="{% url 'shopping_cart_app:allProdCat' %}" class="btn-secondary btn-block">Continue Shopping</a>
            </div>
    </div>
</div><br>
 {% endif %}
{% endblock %}

ecommercewebsiteproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        welcome to the cart
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}-shop cart
    {% else %}
        see our collections -shop cart
    {% endif %}
{% endblock %}

{% block content %}
        {% if category %}
            <div class="row my_row_class">
                <div class="mx-auto">
                    <a href=""> </a>
                </div>
            </div>
        {% else %}
            <div>
                <center><img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt=""></center>
            </div>
        {% endif %}


        <div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}" alt="{{ category.name }}">
        </div><br>
        <div>
            <h1 class="text-centre my_title">{{category.name}}</h1>
            <p class="text-justify">{{category.desc}}</p>
        </div>
        <br>
        {% else %}
<br>
<br>
        <div>
            <h1 class="text-centr my_title">our product collections</h1>
            <p class="text-justify">What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?
            </p>
        </div>
        {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card_img-top my_image" style="width:250px; height:250px;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{ product.name }}</h4>
                    <p>${{ product.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-li btn-sm {% if products.number == pg %} activate{% endif %}"></a>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

ecommercewebsiteproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;Athira Ramesan. All Rights Reserved</p>
</div>

ecommercewebsiteproject/templates/header.html
{% load static %}
<ul class="nav justify-content-end">
    <li class="nav-item ">
        <img src="{%static 'img/anviyalogo.png' %}" style="height: 4rem; width:4rem;">
    </li>
    <li class="nav-item">
      <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
          {%csrf_token%}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Register</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="cart:cart_details">Cart {{item_count}}<i class="fas fa-cart-plus"></i> <span class="sr-only">(current)</span></a>
            {% if item_count > 0 %}
      <li class="nav-item active">
        <a class="nav-link" href=""></a>
      </li>
      {% endif %}
</ul>




<!--<div class="row">-->
<!--  <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ">-->

<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--        <img src="{%static 'img/anviyalogo.png' %}" style="height: 4rem; width:4rem;">-->
<!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--  </button>-->
<!--  <div class="" id="navbarNavDropdown">-->
<!--    <ul class="navbar-nav ms-auto">-->
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="cart:cart_details">Cart {{item_count}}<i class="fas fa-cart-plus"></i> <span class="sr-only">(current)</span></a>-->
<!--            {% if item_count > 0 %}-->
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href=""></a>-->
<!--      </li>-->
<!--      {% endif %}-->

<!--      </li>-->

<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">login</a>-->
<!--      </li>-->
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">register</a>-->
<!--      </li>-->
<!--    </ul>-->
<!--  </div>-->
<!--</nav>-->
<!--</div>-->
<!--</div>-->

ecommercewebsiteproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'shopping_cart_app:allProdCat' %}">HOME</a>
        </li>
        {% for cat in links %}
          <li class="nav-item active">
            <a class="nav-link" href="{{cat.get_url}}">{{ cat.name }}</a>
          </li>
        {% endfor %}
      </ul>
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
    </div>
  </div>
</nav>

ecommercewebsiteproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.desc |truncatewords:155 }}
{% endblock %}

{% block title %}
        {{ product.name }}-shop cart
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p>
            <a href="{% url 'shopping_cart_app:allProdCat' %}">Home</a>
            <a href="{{ product.category.get_url }}"></a>{{product.name}}
        </p>
    </div>
    <div>
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                <img src="{{product.image.url}}" alt="{{ product.name }}">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{ product.name }}</h1>
            <p>${{ product.price }}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{ product.desc }}</p>
            {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b> Out Of Stock </b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
            {% endif %}
        </div>

    </div>
</div>
    </div>
</div>
{% endblock %}

ecommercewebsiteproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        welcome to the cart
    {% endif %}
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text"> You have Searched for: {{query}} </p>
</div>

<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card_img-top my_image" style="width:250px; height:250px;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{ product.name }}</h4>
                    <p>${{ product.price }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p  class="text-center my_search_text"> 0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}